#!/usr/bin/perl
#  
# Author:zhangfeng  cst.feng@gmail.com  2012-07-17

use warnings;
use strict;

use Data::Dumper;

use Storable;

my %total_bytes;

my $sum_bytes = "sum_bytes";
# Sumed data
my $data = "data.txt";
if(-e $data)
{
	my $log = retrieve $data;
}
%total_bytes = %$log;

while(<>)
{
	next if(/^#.*/);
	my ($source, $destination, $bytes) = split;
	$total_bytes{$source}{$destination} += $bytes;
	$total_bytes{$source}{$sum_bytes} += $bytes;
}

store \%total_bytes, $data;
